# Generated by Django 4.2.7 on 2023-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flag_quest", "0003_countryinfo_continent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag_picture", models.CharField(max_length=500)),
                ("your_answer", models.CharField(max_length=500)),
                ("correct_answer", models.CharField(max_length=500)),
            ],
        ),
    ]
