# Generated by Django 4.2.7 on 2023-11-30 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flag_quest", "0004_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="correct_answer",
        ),
    ]
