# Generated by Django 4.2.7 on 2023-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flag_quest", "0006_answer_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="correct_answer",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
