# Generated by Django 5.0.1 on 2024-01-28 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("flag_quest", "0001_initial"),
        ("flag_quest", "0002_countryinfo_test"),
        ("flag_quest", "0003_remove_countryinfo_test"),
        ("flag_quest", "0004_remove_countryinfo_weight"),
        ("flag_quest", "0005_countryinfo_weight"),
        ("flag_quest", "0006_remove_countryinfo_weight_and_more"),
        ("flag_quest", "0007_countryinfo_weight"),
        ("flag_quest", "0008_continent"),
        ("flag_quest", "0009_countryinfo_continent_1"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag_picture", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("your_answer", models.CharField(max_length=500)),
                ("correct_answer", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CountryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("flag_picture", models.CharField(max_length=500)),
                ("capital", models.CharField(max_length=200, null=True)),
                ("continent", models.CharField(max_length=200, null=True)),
                ("meaning_of_flag", models.CharField(default="", max_length=1200)),
                ("weight", models.IntegerField(default=4, null=True)),
                (
                    "continent_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="flag_quest.continent",
                    ),
                ),
            ],
        ),
    ]
