# Generated by Django 4.2.7 on 2023-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flag_quest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryinfo",
            name="test",
            field=models.IntegerField(default=4),
        ),
    ]
