# Generated by Django 4.2.7 on 2023-12-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flag_quest", "0005_countryinfo_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countryinfo",
            name="weight",
        ),
        migrations.AddField(
            model_name="countryinfo",
            name="meaning_of_flag",
            field=models.CharField(default="", max_length=1200),
            preserve_default=False,
        ),
    ]
