# Generated by Django 4.2.7 on 2024-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flag_quest", "0006_remove_countryinfo_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryinfo",
            name="weight",
            field=models.IntegerField(default=4, null=True),
        ),
    ]
