# Generated by Django 4.2.7 on 2024-01-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flag_quest", "0008_continent"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryinfo",
            name="continent_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="flag_quest.continent",
            ),
        ),
    ]
