# Generated by Django 5.0.1 on 2024-01-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flag_quest", "0001_squashed_0009_countryinfo_continent_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countryinfo",
            name="meaning_of_flag",
            field=models.CharField(max_length=1200),
        ),
    ]
