name: Run Pytests on Push

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust as needed

      - name: Set up environment and run Pytests
        run: |
          export DJANGO_SETTINGS_MODULE=flags_game_site.settings
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/flags_game/flags_game  # Adjust path as needed
          pytest
